# Generated by Django 3.2 on 2023-03-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenu',
            old_name='title',
            new_name='main_menu_title',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='title',
            new_name='sub_menu_title',
        ),
    ]
